// The preview thumbnail (spec 9.3).
//
// One still, baked from a real run and embedded in the executable. Not a filmstrip and not a
// cross-fade: the preview pane is a hundred and fifty pixels wide inside a dialog that may close
// before anything animated has said what it is, and one recognisable frame of the cloud says it
// immediately. Not Vulkan either, for the reasons in preview.cpp.
//
// Layout, little-endian: width u32, height u32, then width * height BGRA pixels, top row first.
// That is exactly what a BITMAPINFOHEADER with 32 bits per pixel and a negative height describes,
// so the paint is one StretchDIBits with no repacking and no row padding to get wrong.
//
// Regenerated by capturing a frame and running tools/thumb.py over it; assets/preview_thumb.png is
// the same image in a form a person can look at.
#ifndef NUKE_SAVER_PREVIEW_IMAGE_H
#define NUKE_SAVER_PREVIEW_IMAGE_H

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char* const g_preview_thumb;
extern const unsigned             g_preview_thumb_size;

#ifdef __cplusplus
}
#endif

#endif
