#!/bin/sh
# Emit a C translation unit embedding one binary file as a byte array.
# Usage: embed_blob.sh <out.c> <header> <symbol> <in.bin>
#
# The generated file defines <symbol> as a pointer to the bytes and <symbol>_size as their length,
# both declared by <header>. Same shape as embed_shaders.sh and for the same reason: the build has
# no network and the executable has no companion files, so anything the saver needs at runtime is
# either generated from source or baked in here.

set -e

out=$1
header=$2
sym=$3
in=$4

if [ -z "$out" ] || [ -z "$header" ] || [ -z "$sym" ] || [ -z "$in" ]; then
    echo "usage: embed_blob.sh <out.c> <header> <symbol> <in.bin>" >&2
    exit 1
fi

mkdir -p "$(dirname "$out")"

{
    echo '/* Generated by tools/embed_blob.sh. Do not edit. */'
    printf '#include "%s"\n' "$header"
    echo
    # xxd also emits a <sym>_len; the size below comes from sizeof instead, so drop it rather than
    # ship an unused symbol that -Wall would flag (spec A1 requires a warning-free build).
    xxd -i -n "${sym}_bytes" "$in" \
        | sed 's/^unsigned char/static const unsigned char/' \
        | sed '/^unsigned int .*_len = /d'
    echo
    printf 'const unsigned char* const %s = %s_bytes;\n' "$sym" "$sym"
    printf 'const unsigned %s_size = sizeof(%s_bytes);\n' "$sym" "$sym"
} > "$out"
